import type { ProyectoUnified } from "./types";

export const PROJECTS: ProyectoUnified[] = [
  {
    id: "d1",
    status: "desarrollado",
    title: "BELGRANO  531 ",
    location: "Neuquén",
    year: "2023",
    type: "Mixto",
    imageSrc: "/images/renders/belgrano531.jpg",
    heroImageSrc: "/images/original/belgrano531.jpg",
    slug: "belgrano-531",
    logoSrc: "",
  },
  {
    id: "d2",
    status: "desarrollado",
    title: "GATICA 498 ",
    location: "Neuquén",
    year: "2023",
    type: "Mixto",
    imageSrc: "/images/renders/gatica.jpg",
    heroImageSrc: "/images/original/rendergatica.jpg",
    slug: "gatica-498",
    logoSrc: "",
  },
  {
    id: "d3",
    status: "desarrollado",
    title: " MENDOZA 331 ",
    location: "Neuquén, Mendoza 331",
    year: "2022",
    type: "Residencial",
    imageSrc: "/images/renders/mendoza331.jpg",
    slug: "mendoza-331",
    logoSrc: "",
  },
  {
    id: "d4",
    status: "desarrollado",
    title: " CORDOBA 434",
    location: "Neuquén, Córdoba 434",
    year: "2022",
    type: "Residencial",
    imageSrc: "/images/renders/cordoba434.jpg",
    slug: "cordoba-434",
    logoSrc: "",
  },
  {
    id: "d5",
    status: "desarrollado",
    title: " SALTA 256",
    location: "Neuquén, Salta 256",
    year: "2022",
    type: "Residencial",
    imageSrc: "/images/renders/salta256.jpg",
    slug: "salta-256",
    logoSrc: "",
  },
  {
    id: "d6",
    status: "ejecucion",
    title: " SANTIAGO 611",
    location: "Neuquén, Santiago 611",
    year: "2026",
    type: "Residencial",
    imageSrc: "/images/stgo611/20.jpg",
    slug: "santiago-611",
    logoSrc: "",
  },
  {
    id: "d7",
    status: "ejecucion",
    title: " SANTIAGO 667",
    location: "Neuquén, Santiago 667",
    year: "2026",
    type: "Residencial",
    imageSrc: "/images/renders/santiago667.jpg",
    slug: "santiago-667",
    logoSrc: "",
  },
];
